### ISSUE TITLE
macOS Sierra.4のインストーラが置かれるpath

### ISSUE THREAD

**Issue by Chamiu** [gcch/OS-X-Installation-Disk-Image-Creation-Script#1]
Mac App Storeがinstallerを置く場所ですが、macOS Sierra.3までは/Applicationsでしたが、macOS Sierra.4から次のようになっています。
/Volumes/Install\ macOS\ Sierra/Install\ macOS\ Sierra.app
対応していただけるとうれしいです。

**Comment by gcch** [comment]
appが置かれる場所自体、スクリプト内部と直接関係ないかと思うのですが、ReadmeのUsageを変えてほしいということでしょうか？

**Comment by Chamiu** [comment]
もやっとした書き方をして申し訳ありませんでした。
ReadmeのUsageのOS X Terminal:の５行目の
$ cp "/Applications/Install <os-name>.app" ./
が
$ cp "/Volumes/Install macOS Sierra/Install macOS Sierra.app" ./
になるので、

 macOS Sierra 10.12.3以前は
$ cp "/Applications/Install <os-name>.app" ./
 macOS Sierra 10.12.4以降は
$ cp "/Volumes/Install macOS Sierra/Install macOS Sierra.app" ./

と記述すると分かりやすいのではないかと思われます。

なお、デスクトップにマウントされているのが見えているのに、installer.appが/Applicationになくて探し回る間抜けはわたしくらいだと思いますが...

**Comment by gcch** [comment]
当方 Mac 環境 (macOS Sierra 10.12.3 および 10.12.4) にて、Mac App Store からインストーラ (10.12.4) の再ダウンロードを試してみましたが、これまで同様、/Application 配下にダウンロードされてしまいました。本当にバージョン依存なのか、やや謎です……
時間があるときに再調査したいと思いますが、何か情報 (どんな操作をしたかなど) がありましたら、ご提供ください。

**Comment by gcch** [comment]
何度か再ダウンロードしてみましたが、/Application 配下にダウンロードされる挙動のままのようです。
そもそも /Volumes 配下は外部ストレージ (USBメモリ) やディスクイメージファイルのマウント先なので、Mac App Store からダウンロードした app ファイルがそこに配置されるのは少し考えにくいかなと思っています。あくまで推測ですが、外部ストレージに app ファイルを移動されたのではないかと思われます。 (当方の環境で検証したところ、デスクトップに app ファイルを移動した状態で、Mac App Store で「開く」をクリックしたとき、デスクトップのファイルが開きました。)

変更はなさそうなので、今回はこの調査をもってクローズとさせていただきます。app ファイルを完全に削除した後、Mac App Store からダウンロードしてもやはり /Volumes 配下に配置されるようでしたら、再度 Issue として上げていただければと思います。

**Comment by Chamiu** [comment]
closeになっていますがmacOS Sierraのinstallerが面白い振る舞いをしたので情報提供させてください。
macOS Sierra.5が出たので、macOS Sierra,5をinstall済みの環境で試してみました。
Mac App Store.appがダウンロードする先は/Applicationsです。
ただし、ダウンロードが終了するとinstallerが自動起動され、install開始のwindowが最前面に表示されるタイミングでmountされ、installerが/Applicationsから消えてしまいした。
よって、@gcchさんのscriptにもReadme.mdにも問題はなく、installerを準備するtipsとして、installerが起動し、install開始のwindowが表示されるまでの間にcommand+Qで叩き落とす必要があるようです。
試行回数が１度なので確定的な検証ではありませんが、情報として共有させてください。
